---
# Day 3: Deploy Chrony & PTP4L configuration

- name: Ensure required packages are installed
  apt:
    name:
      - chrony
      - linuxptp
      - gpsd
      - gpsd-clients
      - pps-tools
      - python3-pip
      - python3-dev
    state: present
    update_cache: yes
  become: yes

- name: Configure GPSD
  template:
    src: gpsd.j2
    dest: /etc/default/gpsd
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: restart gpsd

- name: Configure Chrony
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: restart chrony

- name: Configure PTP4L
  template:
    src: ptp4l.conf.j2
    dest: /etc/linuxptp/ptp4l.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: restart ptp4l

- name: Configure PHC2SYS
  template:
    src: phc2sys.conf.j2
    dest: /etc/linuxptp/phc2sys.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: restart phc2sys

- name: Create systemd service for PTP4L
  template:
    src: ptp4l.service.j2
    dest: /etc/systemd/system/ptp4l.service
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: reload systemd

- name: Create systemd service for PHC2SYS
  template:
    src: phc2sys.service.j2
    dest: /etc/systemd/system/phc2sys.service
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: reload systemd

- name: Enable and start services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - gpsd
    - chrony
    - ptp4l
    - phc2sys
  become: yes

# GUI Deployment
- name: Create GUI directory
  file:
    path: /opt/ptp-time-server-gui
    state: directory
    mode: '0755'
  become: yes

- name: Copy GUI app.py file
  copy:
    src: files/gui/app.py
    dest: /opt/ptp-time-server-gui/app.py
    mode: '0755'
  become: yes

- name: Copy GUI requirements.txt file
  copy:
    src: files/gui/requirements.txt
    dest: /opt/ptp-time-server-gui/requirements.txt
    mode: '0644'
  become: yes

- name: Create templates directory for GUI
  file:
    path: /opt/ptp-time-server-gui/templates
    state: directory
    mode: '0755'
  become: yes

- name: Copy GUI template files
  copy:
    src: files/gui/templates/index.html
    dest: /opt/ptp-time-server-gui/templates/index.html
    mode: '0644'
  become: yes

- name: Install GUI Python dependencies
  pip:
    requirements: /opt/ptp-time-server-gui/requirements.txt
    state: present
  become: yes

- name: Create systemd service for GUI
  template:
    src: ptp-gui.service.j2
    dest: /etc/systemd/system/ptp-gui.service
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: reload systemd

- name: Enable and start GUI service
  systemd:
    name: ptp-gui
    enabled: yes
    state: started
  become: yes